[package]
name = "synapseflow-application"
version.workspace = true
edition.workspace = true
description = "SynapseFlow generation application service"
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[dependencies]
synapseflow-domain = { path = "../domain", version = "=0.3.0-dev" }
synapseflow-ports = { path = "../ports", version = "=0.3.0-dev" }

[dev-dependencies]
synapseflow-adapter-in-memory = { path = "../adapters/in-memory", version = "=0.3.0-dev" }

[lints]
workspace = true
