[package]
name = "synapseflow-core"
version.workspace = true
edition.workspace = true
description = "Core components: model loader, shard index, and manifest handling"
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[dependencies]
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
#prost.workspace = true
#tracing.workspace = true
anyhow.workspace = true
thiserror.workspace = true
hex.workspace = true
chrono.workspace = true
uuid.workspace = true

#ring.workspace = true
#ed25519-dalek.workspace = true

# Storage
#sled.workspace = true

[dev-dependencies]
tokio-test = "0.4"

[lints]
workspace = true
